[package]
name = "nameindex"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "NameIndex"
path = "src/main.rs"

[dependencies]
porter-utils = { git = "https://github.com/dtzxporter/porter-lib" }
csv = "1.3.1"
